# Generated by Django 4.2.dev20221115094701 on 2022-11-18 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0078_referenceindex"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0013_footertext_locked_footertext_locked_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserApprovalTaskState",
            fields=[
                (
                    "taskstate_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.taskstate",
                    ),
                ),
            ],
            bases=("wagtailcore.taskstate",),
        ),
        migrations.AlterField(
            model_name="footertext",
            name="locked_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locked_%(class)ss",
                to=settings.AUTH_USER_MODEL,
                verbose_name="locked by",
            ),
        ),
        migrations.CreateModel(
            name="UserApprovalTask",
            fields=[
                (
                    "task_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("wagtailcore.task",),
        ),
    ]
