# Generated by Django 4.0.8 on 2023-01-24 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("base", "0015_person_locked_person_locked_at_person_locked_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="footertext",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
            ),
        ),
        migrations.AddField(
            model_name="footertext",
            name="translation_key",
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
