# Generated by Django 4.2.7 on 2024-02-14 11:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0026_delete_uploadedimage"),
        ("wagtailcore", "0093_uploadedfile"),
        ("recipes", "0001_initial"),
        ("blog", "0006_rename_blogpeoplerelationship_person"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0018_add_genericsettings_and_sitesettings"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Person",
            new_name="Author",
        ),
    ]
