# Generated by Django 4.2.7 on 2024-02-14 11:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0019_rename_person_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name": "Author", "verbose_name_plural": "Authors"},
        ),
    ]
